In [3]:
import numpy as np

In [4]:
ar1 = np.array([0, 1, 2, 3])

In [5]:
ar1 

array([0, 1, 2, 3])

In [6]:
ar2 = np.array([[0, 3, 5],[2, 8, 7]])

In [7]:
ar2

array([[0, 3, 5],
       [2, 8, 7]])

In [8]:
ar2.shape

(2, 3)

In [9]:
ar2.ndim

2

In [10]:
ar3 = np.arange(12)
ar3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
ar4 = np.arange(3, 10, 3)
ar4

array([3, 6, 9])

`ndarray.linspace` generates linear evenly spaced elements between start and end.

In [12]:
ar5 = np.linspace(0, 2.0/3, 4)
ar5

array([ 0.        ,  0.22222222,  0.44444444,  0.66666667])

In [18]:
ar7 = np.ones((2, 3, 2))  # 2 x 3 x 2 array
ar7

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]])

In [19]:
ar8 = np.zeros((4, 2))
ar8

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [21]:
# Produces identity matrix
ar9 = np.eye(3)
ar9

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [24]:
# create diagonal array
ar10 = np.diag((2, 1, 4, 6))
ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [31]:
# rand(m) generates uniformly distributed random numbers 
# with range 0 to m
np.random.seed(100)
ar11 = np.random.rand(9)
ar11

array([ 0.25242635,  0.79566251,  0.01525497,  0.59884338,  0.60380454,
        0.10514769,  0.38194344,  0.03647606,  0.89041156])

In [26]:
# randn(m) produces m normally distributed random numbers
ar12 = np.random.randn(5)
ar12

array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

In [32]:
ar13 = np.empty((3, 2))
ar13

array([[  6.93018288e-310,   1.84988296e-316],
       [  4.65914971e-317,   6.93015319e-310],
       [  6.93018288e-310,   6.93018288e-310]])

In [34]:
# create array from smaller array using tile 
np.array([[1, 2], [6, 7]])


array([[1, 2],
       [6, 7]])

In [35]:
np.tile(np.array([[1,2], [6,7]]), 3)

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [36]:
np.tile(np.array([[1, 2], [6, 7]]), (2, 2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

## Numpy Data types

In [38]:
ar = np.array([2, -1, 6, 3], dtype='float')  # specify data type using dtype parameter
ar

array([ 2., -1.,  6.,  3.])

In [39]:
ar.dtype

dtype('float64')

In [40]:
ar = np.array([2, 3, 5, 8])
ar.dtype

dtype('int64')

In [41]:
ar = np.array([2., 4, 6, 8])
ar.dtype

dtype('float64')

The default dtype is `float`. In case of strings, dtype is length of the longest string in array.

In [42]:
sar = np.array(['Goodbye', 'Welcome', 'Tata', 'Goodnight'])

In [43]:
sar.dtype

dtype('S9')

In [44]:
bar = np.array([True, False, True])
bar.dtype

dtype('bool')

In [45]:
f_ar = np.array([3, -2, 8.18])
f_ar

array([ 3.  , -2.  ,  8.18])

In [46]:
f_ar.astype(int)

array([ 3, -2,  8])

In [47]:
f_ar

array([ 3.  , -2.  ,  8.18])

In [48]:
ar = np.arange(5)
print ar

[0 1 2 3 4]


In [49]:
ar = np.arange(5)
ar[1], ar[-1], ar[0]

(1, 4, 0)

In [50]:
ar = np.arange(5)
ar[::-1]

array([4, 3, 2, 1, 0])

In [51]:
ar = np.array([[2,3,4], [9,8,7], [11, 12, 12]])
ar

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 12]])

In [52]:
ar[1, 1]

8

In [53]:
# set row 1 and column 1 to 5
ar[1, 1] = 5
ar

array([[ 2,  3,  4],
       [ 9,  5,  7],
       [11, 12, 12]])

In [54]:
ar[2]

array([11, 12, 12])

In [55]:
ar[2, :]

array([11, 12, 12])

In [56]:
# Retrieve first column
ar[:,1]

array([ 3,  5, 12])

In [57]:
ar = np.array([0, 1, 2])
ar[5]

IndexError: index 5 is out of bounds for axis 0 with size 3

In [58]:
ar = 2 * np.arange(6)
ar

array([ 0,  2,  4,  6,  8, 10])

In [60]:
ar[1:5:2]  # array slicing

array([2, 6])

In [61]:
ar[1:6:2]

array([ 2,  6, 10])

In [62]:
ar[:4]

array([0, 2, 4, 6])

In [63]:
ar[4:]

array([ 8, 10])

In [64]:
ar[::3]

array([0, 6])

In [65]:
ar[:3]

array([0, 2, 4])

In [66]:
ar[2:]

array([ 4,  6,  8, 10])

In [67]:
ar[2:] = np.ones(4)
ar

array([0, 2, 1, 1, 1, 1])

In [68]:
ar[:3] = 1

In [69]:
ar

array([1, 1, 1, 1, 1, 1])

### Array Masking
Get on specific values using mask array.

In [75]:
np.random.seed(10)
ar = np.random.randint(0, 25, 10)  # random integers
ar

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

In [76]:
even_mask = (ar % 2 ==0);
even_mask

array([False,  True, False,  True, False,  True, False,  True, False,  True], dtype=bool)

In [77]:
even_nums = ar[even_mask]
even_nums

array([ 4,  0, 16,  8,  0])

In [80]:
ar = np.array(['Hungary', 'Nigeria', 'Guatemala', '', 'Poland', '', 'Japan'])
ar

array(['Hungary', 'Nigeria', 'Guatemala', '', 'Poland', '', 'Japan'],
      dtype='|S9')

In [82]:
ar[ar=='']='USA'  # set array value to USA where it was empty string
ar

array(['Hungary', 'Nigeria', 'Guatemala', 'USA', 'Poland', 'USA', 'Japan'],
      dtype='|S9')

In [86]:
ar = 11 * np.arange(0, 10)  # multiply 11 to all elements
ar

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [87]:
ar[[1,3,4,2,7]]

array([11, 33, 44, 22, 77])

In [88]:
ar[1,2,4]  # gives error because we are trying to access too many elements.

IndexError: too many indices for array

In [89]:
ar[[1,3]] = 50
ar

array([ 0, 50, 22, 50, 44, 55, 66, 77, 88, 99])

### Complex Indexing

In [90]:
ar = np.arange(15)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [92]:
ar2 = np.arange(0, -10, -1)[::-1]  # create from the end
ar2

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0])

In [95]:
ar[:10]=ar2
ar

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0, 10, 11, 12, 13, 14])

In [96]:
ar1 = np.arange(12)
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [98]:
ar2 = ar1[::2]
ar2

array([ 0,  2,  4,  6,  8, 10])

In [99]:
ar2[1]=-1
ar1  # 3rd element of ar1 has changed.

array([ 0,  1, -1,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [100]:
ar2

array([ 0, -1,  4,  6,  8, 10])

In [101]:
print np.may_share_memory(ar1, ar2)

True


To force Numpy to copy an array, we use `np.copy` method.

In [102]:
ar = np.arange(8)
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [103]:
arc = ar[:3].copy()
arc

array([0, 1, 2])

In [104]:
arc[0]=-1
arc

array([-1,  1,  2])

In [105]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

## Operations

In [106]:
ar = np.arange(0, 7) * 5
ar

array([ 0,  5, 10, 15, 20, 25, 30])

In [107]:
ar = np.arange(5) ** 4
ar

array([  0,   1,  16,  81, 256])

In [108]:
ar ** 0.5

array([  0.,   1.,   4.,   9.,  16.])

In [109]:
ar.astype('int')

array([  0,   1,  16,  81, 256])

In [115]:
ar2 = (ar**0.5).astype('int')
ar2

array([ 0,  1,  4,  9, 16])

In [121]:
ar = 3 + np.arange(0, 30, 3)
ar

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [117]:
ar2 = np.arange(1, 11)
ar2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [122]:
ar.size

10

In [123]:
ar2.size

10

In [124]:
ar - ar2 

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [125]:
ar / ar2

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [126]:
ar * ar2

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

In [127]:
ar = np.arange(1000)
%timeit [ar[i] ** 3 for i in ar]

1000 loops, best of 3: 379 µs per loop


In [128]:
ar = range(1000)

In [129]:
%timeit [ar[i] ** 3 for i in ar]

The slowest run took 12.02 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 90.7 µs per loop


Array multiplication is element-wise. For matrix multiplication, use `dot` operator.

In [133]:
ar = np.array([[1, 1], [1, 1,]])
ar

array([[1, 1],
       [1, 1]])

In [134]:
ar2 = np.array([[2, 2], [2, 2]])
ar2

array([[2, 2],
       [2, 2]])

In [135]:
ar.dot(ar2)

array([[4, 4],
       [4, 4]])

### Logical operators and comparisons

In [136]:
ar = np.arange(1, 5)
ar

array([1, 2, 3, 4])

In [138]:
ar2 = np.arange(5, 1, -1)
ar2

array([5, 4, 3, 2])

In [140]:
ar < ar2   # element wise comparison

array([ True,  True, False, False], dtype=bool)

In [141]:
l1 = np.array([True, False, True, False])
l2 = np.array([False, False, True, False])
np.logical_and(l1, l2)

array([False, False,  True, False], dtype=bool)

Numpy operators like log, sin, cos and exp are also element-wise.

In [142]:
ar = np.array([np.pi, np.pi /2])
np.sin(ar)

array([  1.22464680e-16,   1.00000000e+00])

**Caution**: For element-wise operation, two arrays **must** have same shape.

In [144]:
ar = np.array([[1,2,3],[4,5,6]])
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
ar.T   # transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [146]:
np.transpose(ar)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [147]:
# Array wise comparison not element-wise
ar = np.arange(0, 6)
ar2 = np.array([0, 1, 2, 3, 4, 5])
np.array_equal(ar, ar2)

True

In [148]:
np.all(ar == ar2)

True

### Reduction operations (Aggregation)

In [151]:
ar = np.arange(1, 6)
ar.prod()   # product

120

In [152]:
ar = np.array([np.arange(1, 6), np.arange(1,6)])
ar

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [153]:
np.prod(ar, axis=0)  # column element product

array([ 1,  4,  9, 16, 25])

In [154]:
np.prod(ar, axis=1)   # row element product

array([120, 120])

In [155]:
ar = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
ar.sum()

54

In [156]:
ar.mean()   # average

6.0

In [157]:
np.median(ar)   # middle value

6.0

In [159]:
np.random.seed(10)
ar = np.random.randint(0, 10, size=(4, 5))
ar

array([[9, 4, 0, 1, 9],
       [0, 1, 8, 9, 0],
       [8, 6, 4, 3, 0],
       [4, 6, 8, 1, 8]])

In [162]:
ar.mean()  # mean

4.4500000000000002

In [163]:
ar.std()   # standard deviation

3.4274626183227732

In [164]:
ar.var(axis=0)  # variance for each column

array([ 12.6875,   4.1875,  11.    ,  10.75  ,  18.1875])

In [165]:
ar.cumsum()   # cumulative sum

array([ 9, 13, 13, 14, 23, 23, 24, 32, 41, 41, 49, 55, 59, 62, 62, 66, 72,
       80, 81, 89])

In [166]:
ar.sum()

89

In [167]:
np.random.seed(100)
ar=np.random.randint(1, 10, size=(4, 4))
ar

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5]])

In [168]:
np.any((ar % 7 == 0))  # any element divisible by 7

False

In [169]:
np.all(ar < 11)  # all elements less than 11

True

### Broadcasting

Broadcasting gives ability to combine arrays that don't have exact shape.

In [171]:
ar = np.ones([3, 2])
ar

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [172]:
ar2 = np.array([2,3 ])
ar2

array([2, 3])

In [173]:
ar + ar2

array([[ 3.,  4.],
       [ 3.,  4.],
       [ 3.,  4.]])

In [177]:
ar = np.array([[23, 24, 25]])
ar

array([[23, 24, 25]])

In [178]:
ar.T

array([[23],
       [24],
       [25]])

In [179]:
ar.T + ar

array([[46, 47, 48],
       [47, 48, 49],
       [48, 49, 50]])

## Shape manipulation

In [180]:
ar = np.array([np.arange(1,6), np.arange(10, 15)])
ar

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [182]:
ar.ravel()   # flatten array

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [183]:
ar.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

In [184]:
# reshape can be used to change the shape or unflatten
ar = np.arange(1, 16)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [185]:
ar.reshape(3, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

`ndarray` operator resizes array in place. `numpy.resize` returns a new array with the specified shape.

In [186]:
ar = np.arange(5)
ar.resize((8, ))
ar

array([0, 1, 2, 3, 4, 0, 0, 0])

In [187]:
ar

array([0, 1, 2, 3, 4, 0, 0, 0])

In [188]:
ar=np.arange(5)
ar

array([0, 1, 2, 3, 4])

In [189]:
ar2 = ar

In [190]:
ar.resize((8,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

In [191]:
np.resize(ar, (8,))

array([0, 1, 2, 3, 4, 0, 1, 2])

In [192]:
ar = np.array([14, 15, 16])

In [194]:
ar.shape

(3,)

In [195]:
ar = ar[:, np.newaxis]
ar.shape

(3, 1)

In [196]:
ar

array([[14],
       [15],
       [16]])

### Array sorting

In [197]:
ar = np.array([[3,2], [10, -1]])
ar

array([[ 3,  2],
       [10, -1]])

In [200]:
ar.sort(axis=1)  # along row
ar

array([[ 2,  3],
       [-1, 10]])

In [203]:
ar.sort(axis=0)
ar

array([[-1,  3],
       [ 2, 10]])

In [205]:
ar = np.array([[3,2], [10,-1]])
ar

array([[ 3,  2],
       [10, -1]])

To sort in place `np.array.sort`.

In [207]:
ar

array([[ 3,  2],
       [10, -1]])

In [215]:
ar = ar.ravel()
ar

array([ 3,  2, 10, -1])

In [216]:
ar.argmin()  # index of minimum value

3

In [218]:
ar.max()

10

In [219]:
ar.var()

16.25

In [220]:
ar.std()

4.0311288741492746

In [221]:
ar.argmax()

3