# Tensorflow

Tensorflow is open source library for numerical computation using data flow graphs. It's data model comprises of tensors, which are basic data units created, manipulated and saved in Tensorflow program. Programming model consists of data flow graphs. Execution model consists of firing nodes of a computation graph in a sequence of dependence.

In [2]:
import tensorflow as tf
tf.__version__

'1.13.1'

You can create interactive Tensorflow session using `tfs = tf.InteractiveSession()`. The only difference is that with Interactive session, we get results instantaneously.

In [3]:
tfs = tf.InteractiveSession()

In [4]:
hello = tf.constant("Hello tensorflow")

In [5]:
print(tfs.run(hello))

b'Hello tensorflow'


**Tensors** are basic elements of computation and a fundamental data structure in Tensorflow. A tensor is an n-dimensional collection of data, identified ny rank, shape and type. *Rank* is the dimension of a tensor, *shape* is the list denoting size in each dimension. A scalar value in a tensor is of rank 0 and has shape of [1].

Tensorflow can be created in following ways.
- By defining constants, operations and variables and passing the values to their constructor.
- By defining placeholders and passing the values to `session.run()`.
- By converting Python objects with `tf.convert_to_tensor()` function.

Constant valued tensor is created using `tf.constant(value, dtype=None, shape=None, name='Const', verify_shape=False)`

In [6]:
c1 = tf.constant(5, name='x')
c2 = tf.constant(6.0, name='y')
c3 = tf.constant(7.0, tf.float32, name='z')

In [7]:
print(c1); print(c2); print(c3);

Tensor("x:0", shape=(), dtype=int32)
Tensor("y:0", shape=(), dtype=float32)
Tensor("z:0", shape=(), dtype=float32)


In order to populate these tensors with value, we need to run it through session.

In [8]:
print(tfs.run([c1, c2, c3]))

[5, 6.0, 7.0]


In [9]:
op1 = tf.add(c2, c3)
print(op1)

Tensor("Add:0", shape=(), dtype=float32)


In [10]:
op2 = tf.multiply(c2, c3)

In [11]:
print(tfs.run(op1))
print(tfs.run(op2))

13.0
42.0


| Operation Type | Opeartions |
|:---------------:|:----------:|
| Arithmetic operation | tf.add, tf.subtract, tf.multiply, tf.scalar_mul, tf.div, tf.divide, tf.truediv, tf.floordiv, tf.realdiv, tf.truncatediv, tf.floor_div, tf.truncatemod, tf.floormod, tf.mod, tf.cross |
| Math opeartions | tf.add_n, tf.abs, tf.negative, tf.sign, tf.reciprocal, tf.square, tf.round, tf.sqrt, tf.rsqrt, tf.pow, tf.exp, tf.expm1, tf.log, tf.log1p, tf.ceil, tf.floor, tf.maximum, tf.minimum, tf.cos, tf.sin, tf.lbeta, tf.tan, tf.acos, tf.asin, tf.atan, tf.lgamma, tf.digamma, tf.erf, tf.erfc, tf.igamma, tf.squared_difference, tf.igammac, tf.zeta, tf.polygamma, tf.betainc, tf.rint |
| Matrix Math operations | tf.diag, tf.diag_part, tf.trace, tf.transpose, tf.eye, tf.matrix_diag, tf.matrix_diag_part, tf.matrix_band_part, tf.matrixz_set_diag, tf.matrix_transpose, tf.matmul, tf.norm, tf.matrix_determinant, tf.matrix_inverse, tf.cholesky, tf.cholesky_solve, tf.matrix_solve, tf.matrix_triangular_solve, tf.matrix_solve_ls, tf.qr, tf.self_adjoint_eig, tf.self_adjoint_eigvals, tf.svd |
| Tensor Math operations | tf.tensordot |
| Complex number oprerations | tf.complex, tf.conj, tf.imag, tf.real |
| String operations | tf.string_to_hash_bucket_fast, tf.string_to_hash_bucket_strong, tf.as_string, tf.encode_base64, tf.decode_base64, tf.reduce_Join, tf.string_join, tf.string_split, tf.substr, tf.string_to_hash_Bucket |

The placeholders allow us to create tensors whose values can be provided at runtime. It provides `tf.placeholder()` method for this which looks like this.

```python
tf.placeholder(dtype, shape=None, name=None)
```

In [12]:
p1 = tf.placeholder(tf.float32)
p2 = tf.placeholder(tf.float32)
print(p1); print(p2)

Tensor("Placeholder:0", dtype=float32)
Tensor("Placeholder_1:0", dtype=float32)


In [13]:
op4 = p1 * p2
print('run (op4, {p1: 2.0, p2: 3.0}): ', tfs.run(op4, {p1: 2.0, p2: 3.0}))

run (op4, {p1: 2.0, p2: 3.0}):  6.0


We can specify the dictionary using `feed_dict` parameter in the `run()` operation.

In [14]:
print(tfs.run(op4, feed_dict={p1: 2.0, p2: 4.0}))

8.0


In [15]:
print(tfs.run(op4, feed_dict = {p1: [2.0, 3.0, 4.0], p2: [3.0, 4.0, 5.0]}))

[ 6. 12. 20.]


We can create tensors from Python objects such as lists and NumPy arrays using `tf.convert_to_tensor()` operation.

```python
tf.convert_to_tensor(value, dtype=None, name=None, preferred_dtype=None)
```

In [16]:
# Create 0-D tensor
tf_t = tf.convert_to_tensor(5.0, dtype=tf.float64)
print(tfs.run(tf_t))

5.0


In [17]:
import numpy as np

In [18]:
# Create 1-D tensor
a1dim = np.array([1,2,3,4,5.99])
print(a1dim.shape)
tf_t = tf.convert_to_tensor(a1dim, dtype=tf.float64)
print(tf_t)
print(tf_t[2])

(5,)
Tensor("Const_2:0", shape=(5,), dtype=float64)
Tensor("strided_slice:0", shape=(), dtype=float64)


In [19]:
tfs.run(tf_t)

array([1.  , 2.  , 3.  , 4.  , 5.99])

In [20]:
a2dim = np.array([(1,2,3,4,5.99),
                  (2,3,4,5,6.99),
                  (3,4,5,6,7.99)
                 ])
print(a2dim.shape)
tf_t = tf.convert_to_tensor(a2dim, dtype=tf.float64)
print(tf_t[0][0])
print(tf_t)

(3, 5)
Tensor("strided_slice_2:0", shape=(), dtype=float64)
Tensor("Const_3:0", shape=(3, 5), dtype=float64)


In [21]:
print(tfs.run(tf_t))

[[1.   2.   3.   4.   5.99]
 [2.   3.   4.   5.   6.99]
 [3.   4.   5.   6.   7.99]]


In [22]:
print(tfs.run(tf_t[0][0]))

1.0


In Tensorflow, variables are tensor objects that hold values that can be modified during the execution of the program. `tf.placeholder` defines input data that does not change over time. `tf.Variable` defines variable values that are modified over time. `tf.placeholder` does not need an initial value at the time of definition. `tf.Variable` needs an initial value at the time of definition.

$ y = W $ x $ x + b $

In [23]:
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
x = tf.placeholder(tf.float32)
y = w * x + b

print('w:', w);
print('b:', b)
print('x:', x)
print('y:', y)

Instructions for updating:
Colocations handled automatically by placer.
w: <tf.Variable 'Variable:0' shape=(1,) dtype=float32_ref>
b: <tf.Variable 'Variable_1:0' shape=(1,) dtype=float32_ref>
x: Tensor("Placeholder_2:0", dtype=float32)
y: Tensor("add_1:0", dtype=float32)


Before we can use the variables in Tensorflow session, they have to be initialized using `initializer` operation.

In [24]:
tfs.run(w.initializer)

In practice, we use a convenience function by Tensorflow to initialize all the variables using `tf.global_variables_initializer()` method. It could also be executed using `tf.global_variables_initializer().run()`. We can also initialize specific variables using `tf.variables_initializer()` function.

In [25]:
tfs.run(tf.global_variables_initializer())

In [26]:
print('run(y, {x: [1,2,3,4]}):', tfs.run(y, {x: [1,2,3,4]}))

run(y, {x: [1,2,3,4]}): [0.         0.3        0.6        0.90000004]


Tensors can also be generated from various TensorFlow functions.

In [27]:
# generate a vector of 100 zeroes and print it.
a = tf.zeros((100,))
print(tfs.run(a))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


- `zeros(shape, dtype=tf.loat32, name=None)` : Creates a tensor with all elements zero.
- `zeros_like(tensor, dtype=None, name=None, optimize=True)` : creates a Tensor of same shape as argument, with all elements set to zero.
- `ones(shape, dtype=tf.float32, name=None)` : Creates a tensor with all elements set to one.
- `ones_like(tensor, dtype=None, name=None, optimize=True)` : Creates a tensor of same shape as argument, with all elements set to one.
- `fill(dims, value, name=None)` : Creates a tensor of shape as `dims` argument with all elements set to `value`; for example, `a = tf.fill([100], 0)`.
- `lin_space(start, stop, num, name=None)` : Generates a 1-D tensor from a sequence of `num` numbers within the range [start, stop]. Tensor has same data type as `start` argument.
- `range(start, limit, delta=1, dtype=None, name='range')` : generates 1-D tensor.
- `random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)` : generates a tensor of specific shape, filled with values from a normal distribution.
- `truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)` : generates a tensor of specific shape, filled with values from truncated normal distribution. Truncated means that the values returned are always at a distance less than two standard deviations from the mean.
- `random_unifrom(shepa,minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)` : generates a tensor filled with values from a uniform distribution.
- `random_gamma(shape, alpha, beta=None, dtype=tf.float32, seed=None, name=None)` : generates tensor filled with values from gamma distributions.

If we define a variable with a name that has been defined before, then TensorFlow throws an exception. The function `tf.get_variable()` returns the existing variable with the same name if it exists.

In [28]:
w = tf.get_variable(name='w', dtype=tf.float32, initializer=[.3])
b = tf.get_variable(name='b', dtype=tf.float32, initializer=[-.3])

In distributed TensorFlow, `tf.get_variable()` gives us global variables. To get the local variables TensorFlow has a function with similar signature: `tf.get_local_variable()`. If `reuse` flag is not set by using `tf.variable_scope.reuse_variable()` or `tf.variable.scope(reuse=True)`, getting already defined variables will throw an exception.

A **data flow graph** or **computation graph** is the basic unit of computation in TF. A computation graph is made up of nodes and edges. Each node represents an operation and each edge represents a tensor that gets transferred between nodes. Tensorflow programs are made up of two kinds of operations.
1. Building the computation graph
2. Running the computation graph

Tensorflow comes with default graph. Unless another graph is specified, a new node gets implicitly added to the default graph. We can get explicit access to default graph using `graph = tf.get_default_graph()`. We can execute the operation objects and evaluate tensor objects using session object.

In [29]:
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
# Define model input and output
x = tf.placeholder(tf.float32)
y = w * x + b
output = 0
with tf.Session() as tfs:
    tf.global_variables_initializer().run()
    output = tfs.run(y, {x: [1,2,3,4]})
print('output: ', output)

output:  [0.         0.3        0.6        0.90000004]


The nodes are executed in the order of dependency. If we want to control the order in which the nodes are executed in the graph, we can achieve this using `tf.Graph.control_dependencies()`

```python
with graph_variable.control_dependencies([c,d]):
    # other statements
```

If the graph has nodes a,b,c and d and you want to execute c and d before a and b, above statement helps. This ensures that any node in `with` block is executed only after nodes c and d have been executed.

A graph can be divided into multiple parts and each part can be placed and executed on separate devices, such as CPU or GPU. We can list all devices available for graph execution with below command.

```python
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
```

Tensorflow implicitly distributes the code across the CPU units and thus by default it shows single CPU. When Tensorflow starts executing graphs, it runs the independent paths within each graph in a separate thread on a separate CPU. We can restrict the number of threads used for this purpose by changing the number of `inter_op_parallelism_threads`. If within an independent path, an operation is capable of running on multiple threads, TensorFlow will launch that operation on multiple threads. The number of threads in this pool can be changed by `intra_op_parallelism_threads`.

We can enable logging of variable placement by defining a config object and setting `log_device_placement` to `true`.

In [30]:
tf.reset_default_graph()
tf.__version__

'1.13.1'

In [31]:
w = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
x = tf.placeholder(tf.float32)
y = w * x + b
config = tf.ConfigProto()
config.log_device_placement=True
with tf.Session(config=config) as tfs:
    tfs.run(tf.global_variables_initializer())
#     tfs.global_variables_initializer().run()
    print('output', tfs.run(y, {x:[1,2,3,4]}))

output [0.         0.3        0.6        0.90000004]


The variables and operations can be placed on a specific devices by using `tf.device()` function. Let's say we want to place graph on the CPU.

```python
tf.reset_default_graph()
with tf.device('/device:CPU:0'):
    w = tf.get_variable(name='w', initializer=[.3], dtype=tf.float32)
    b = tf.get_variable(name='b', initializer=[-.3], dtype=tf.float32)
    x = tf.placeholder(name='x', dtype=tf.float32)
    y = w * x + b
config = tf.ConfigProto()
config.log_device_placement=True

with tf.Session(config=config) as tfs:
    tfs.run(tf.global_variables_initializer())
    print('output:', tfs.run(y, {x:[1,2,3,4]}))
```

Tensorflow follows these placement rules simply:

If graph was previously run, the node is left on the device where it was placed earlier.
Else if the `tf.device()` block is used, the node is placed on the specified device.
Else if the GPU is present, then the node is placed on first available GPU.
Else if GPU is not present, then node is placed on the CPU.

We can create complicated algorithm for a function which returns device string and we can place node on that device by passing this function to `tf.device()` function. Tensorflow has round robin device setter in `tf.train.replica_device_setter()`.

When we place a Tensorflow operation on GPU, the TF must have GPU implementation of that operation (kernel). If it is not present, it results in runtime error. We also get runtime error if that GPU is not present. The best option is to place it on CPU if GPU is not present using `config.allow_soft_placement=True`.

When we start running TF session, by default it grabs all GPU memory. If we run another session, we get out of memory error. This could be solve as below.
- For multi-GPU systems, set `os.environ['CUDA_VISIBLE_DEVICES'] = '0'`. The code after this setting will be able to grab all memory of only visible GPU.
- We can set raction to allocate a percentage of memory using `config.gpu_options.per_process_gpu_memory_fraction = 0.5`. This will allocate 50% of the memory of all GPU devices.
- We can also limit the TF process to grab only minimum required memory at the start of process. Later, we can set a config option to allow the growth of memory using `config.gpu_options.allow_growth=True`. This allows only allocated memory to grow, but memory is never released back.

We can also create graphs separate from defualt graph and execute them in a session. It is not recommended because creating and using multiple graphs in the same program would require multiple TF sessions and each session would consume heavy resources. Secondly, we cannot directly pass data in between sessions.

```python
g = tf.Graph() # create new graph
output = 0
# execute with new graph
with g.as_default():
    w = tf.Variable([.3], tf.float32)
    b = tf.Variable([-.3], tf.float32)
    x = tf.placeholder(tf.float32)
    y = w * x + b
    
with tf.Session(graph=g) as tfs:
    tf.global_variable_initializer().run()
    output = tfs.run(y, {x:[1,2,3,4]})
print('output:', output)
```

## TensorBoard

TensorBoard visualizes computation graph structure, provides statistical analysis and plots the values captured as summaries during the execution of graphs.

In [32]:
# start defining variables for linear model
w = tf.Variable([.3], dtype=tf.float32, name='w')
b = tf.Variable([-.3], dtype=tf.float32, name='b')
x = tf.placeholder(name='x', dtype=tf.float32)
y = w * x + b
with tf.Session() as tfs:
    tfs.run(tf.global_variables_initializer())
    writer = tf.summary.FileWriter('tflogs', tfs.graph)
    print(tfs.run(y, feed_dict={x:3}))

[0.6]


We cam run tensorboard from shell using `tensorboard --logdir='tflogs'` and open *localhost:6006* url to view Tensorboard.